title: Allgemein
blueprint: globals
data:
  site_name: 'Mosaik Church'
  address: |
    Mosaik Church Stuttgart
    Römerstraße 10
    70178 Stuttgart
  map_link:
    google_maps: 'https://goo.gl/maps/7D2mGVBakt12'
    apple_maps: 'http://maps.apple.com/?address=Mosaik+Church+Stuttgart&t=m'
  services:
    '10:00 Uhr': 'mit Kids Church'
    '11:30 Uhr': 'mit anschließendem Next Steps Kurs'
  social_media:
    -
      type: platform
      name: Instagram
      icon: instagram
      link: 'https://instagram.com/mosaik_church'
      enabled: true
    -
      type: platform
      name: Facebook
      icon: facebook
      link: 'https://facebook.com/MosaikStuttgart'
      enabled: true
