title: Default
taxonomies: false
sections:
  main:
    display: Main
    fields:
      rich_content:
        fieldset: bard
        type: partial
        display: Content
  sidebar:
    display: Seiteninfos
    fields:
      header_image:
        container: main
        folder: /images
        restrict: false
        max_files: 1
        type: assets
        display: Hintergrundbild
        mode: grid
      analytics:
        type: google_analytics
        display: Analytics
