title: Sonntag
hide: true
taxonomies: false
sections:
  main:
    display: Main
    fields:
      current_series:
        max_items: 1
        mode: panes
        label: '{{ title }}'
        taxonomy: sermon_series
        type: taxonomy
        display: 'Aktuelle Predigtserie'
      rich_content:
        fieldset: bard
        type: partial
        display: Content
  sidebar:
    display: Seiteninfos
    fields:
      header_image:
        container: main
        folder: /images
        restrict: false
        max_files: 1
        type: assets
        display: Hintergrundbild
        mode: grid
