title: Sonntag
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
      -
        handle: current_series
        field:
          type: terms
          max_items: 1
          mode: panes
          label: '{{ title }}'
          taxonomies:
            - sermon_series
          display: 'Aktuelle Predigtserie'
      -
        import: bard
  sidebar:
    display: Seiteninfos
    fields:
      -
        handle: header_image
        field:
          type: assets
          container: main
          folder: /images
          restrict: false
          max_files: 1
          display: Hintergrundbild
          mode: grid
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
