routes:
  /users: user/index
  '/users/{username}': user/profile
  /account: user/account
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /podcast/feed:
    layout: feed
    content_type: application/rss+xml
  /live:
    template: livestream
    load: /besuche-uns/live
collections:
  podcasts: '/media/{slug}'
taxonomies:
  sermon_series: '/media/serie/{slug}'
redirect:
  /login: /cp
  /besuche-uns/gottesdienst: /live
  /mitmachen/homezones/homezone-finden.html: /mitmachen/homezones/homezonefinder
  /homezones.html: /mitmachen/homezones
  /medien/predigten.html: /media/predigten
  /mitmachen/sommerbibelschule.html: /mitmachen/sommerbibelschule
  /medien/predigten/detail/sermon/gesunde-sexualitaet.html: /media/gesunde-sexualitaet
  '/medien/*': /
