routes:
  /blog/tags: blog/taxonomies
  /login:
    redirect: /cp
  /users: user/index
  '/users/{username}': user/profile
  /account: user/account
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /podcast/feed:
    layout: feed
    content_type: atom
  /live:
    template: livestream
    load: /besuche-uns/live
  /besuche-uns/gottesdienst:
    redirect: /live
collections:
  podcasts: '/media/{slug}'
taxonomies:
  sermon_series: '/media/serie/{slug}'
