routes:
  /login:
    redirect: /cp
  /users: user/index
  '/users/{username}': user/profile
  /account: user/account
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /podcast/feed:
    layout: feed
    content_type: application/rss+xml
  /live:
    template: livestream
    load: /besuche-uns/live
  /besuche-uns/gottesdienst:
    redirect: /live
  /mitmachen/homezones/homezone-finden.html:
    redirect: /mitmachen/homezones/homezonefinder
  /medien/predigten.html:
    redirect: /media/predigten
  /homezones.html:
    redirect: /mitmachen/homezones
  /mitmachen/sommerbibelschule.html:
    redirect: /mitmachen/sommerbibelschule
collections:
  podcasts: '/media/{slug}'
taxonomies:
  sermon_series: '/media/serie/{slug}'
